### PR TITLE
LB-272: Add support for testing on Jenkins (ci.metabrainz.org)

### PR DESCRIPTION
**Pull request by paramsingh**
Just testing, pls ignore.

### CODE REVIEW

**Comment by paramsingh** [comment]
@brainzbot test this please

**Comment by paramsingh** [comment]
@brainzbot test this please

**Comment by paramsingh** [comment]
@brainzbot test this please

**Comment by paramsingh** [comment]
@brainzbot retest this please

**Comment by paramsingh** [comment]
@brainzbot retest this please

**Comment by paramsingh** [comment]
Okay, Jenkins works for messybrainz now. :tada:

**Comment by paramsingh** [comment]
https://ci.metabrainz.org/job/MessyBrainz/19/

**Review by mayhem — APPROVED** [review]
🎄 !!

**Pull request merged**
