### PR TITLE
LB-86: Add support for creation of data dumps from manage.py

### PR DESCRIPTION
**Pull request by paramsingh**
This is mostly code reused from LB. 

One thing to do would be adding a table to keep track of dumps (for future incremental dumps).

Also, did a small restructure by creating a `db` folder instead of just a single `db.py`. I took a look and I don't think it should cause any regressions but another look would be nice to have.

### CODE REVIEW

**Comment by alastair** [comment]
> This is mostly code reused from LB.

Is it worth putting part of this in brainzutils and make it usable for all pythonbrainzes?

**Comment by paramsingh** [comment]
I thought about that but every Brainz has it's own stuff that makes it need a dump module anyways (AB has its JSON dumps, LB has the listens dump), so I wasn't sure if it was worth it.

**Comment by paramsingh** [comment]
Added a ticket for more discussion on this: https://tickets.metabrainz.org/projects/BU/issues/BU-6?filter=allopenissues

**Comment by paramsingh** [comment]
Closing this as the repository has been merged into [listenbrainz-server](https://github.com/metabrainz/listenbrainz-server).

**Pull request closed without merging**
