### PR TITLE
LB-394: Upgrade MessyBrainz flask to 1.0.2

### PR DESCRIPTION
**Pull request by Ge0rg3**
# Summary

Update BrainzUtils to 1.7.0, and so Flask also updates to 1.0.
All tests pass, and I can't find any errors when browsing the site.

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [x] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:
Update BrainzUtils in requirements.txt.

Related ticket: [LB-394](https://tickets.metabrainz.org/browse/LB-394)

### CODE REVIEW

**Comment by paramsingh** [comment]
@brainzbot add to whitelist

**Comment by kartikeyaSh** [comment]
@Ge0rg3 flask 1.0.2 has requirement Werkzeug>=0.14, but we use werkzeug 0.10.4 in MsB which is incompatible. That must be updated too.

**Comment by alastair** [comment]
Good catch!
if BrainzUtils itself depends on Werkzeug then we don't need an explicit reference in requirements for it.

**Comment by Ge0rg3** [comment]
test

**Pull request closed without merging**
