### PR TITLE
LB-271: Add tests for messybrainz.data functions

### PR DESCRIPTION
**Pull request by paramsingh**
Add docstrings to functions and add tests.

Also, found a small bug in `get_id_from_meta_hash` where it constructed the metadata incorrectly. The function doesn't seem like it is used anywhere though, so no biggie, I guess.

### CODE REVIEW

**Comment by paramsingh** [comment]
I'll rebase and make this work with Jenkins once #30 gets merged. Right now, db tests probably won't be run.

**Comment by paramsingh** [comment]
Did a rebase but some problems still exist, I'll take a look in a few hours.

**Comment by paramsingh** [comment]
I moved `webserver` into `messybrainz` for consistency with other Flask projects and so that the code coverage thingy works correctly without needing to hack stuff into the jenkins build script. Makes this a bigger PR but would be better overall. I don't think this should cause problems with how MessyBrainz works with ListenBrainz, but we should be a bit cautious here. I'll test this branch out with LB in some time and report back.

**Comment by paramsingh** [comment]
I ran tests on travis with this branch of messybrainz and they all pass. https://travis-ci.org/paramsingh/listenbrainz-server/builds/321434387

**Review by mayhem — APPROVED** [review]
Lots of stuff, but most of it seems copy pasta for consistency, right?

**Comment by paramsingh** [comment]
Almost entirely `git mv` tbh :D

**Comment by mayhem** [comment]
Ok, feel free to merge when you're happy.

**Pull request merged**
