### PR TITLE
LB-349: MessyBrainz: Don't need to initialize database engine before every request.

### PR DESCRIPTION
**Pull request by kartikeyaSh**

### CODE REVIEW

**Comment by mayhem** [comment]
I'm very hesitant about this one -- I think we need to be very clear as to why MsB does it one way and LB does it another way.

**Comment by paramsingh** [comment]
@brainzbot, add to whitelist

**Comment by alastair** [comment]
I'll take a look - I have a suspicion that it's different to the others because at this time we were still learning about the best way to do flask/postgres/sqlalchemy and this is still an older variation of what we tried. I'll let you know

**Comment by paramsingh** [comment]
@brainzbot retest this please

**Review by alastair — APPROVED** [review]
I can't even remember why I did it this way in the first place... It's probably a holdback from when we were directly using psycopg2
Anyway, a few points:
 - All of our other apps do init_db_connection in the create_app method
 - We don't currently run the MsB API for interaction with LB anyway, so this isn't actually used
 - From SQLAlchemy documentation at http://docs.sqlalchemy.org/en/latest/core/engines.html#pooling - "Since the Engine is essentially “home base” for the connection pool, it follows that you should keep a single Engine per database established within an application, rather than creating a new one for each connection."

All of that to say, looks good 👍

**Pull request merged**
